version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "src/backend/webapp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "src/client/test-client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
